language: php

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash

php:
  - 5.5
  - 5.6

script:
  - phpcs --report-full --standard=PSR2 include/ccache.php
  - phpcs --report-full --standard=PSR2 include/crypt.php
  - phpcs --report-full --standard=PSR2 include/db.php
  - phpcs --report-full --standard=PSR2 include/digest.php
  - phpcs --report-full --standard=PSR2 include/feedbrowser.php
  - phpcs --report-full --standard=PSR2 include/functions2.php
  - phpcs --report-full --standard=PSR2 include/labels.php
  - phpcs --report-full --standard=PSR2 include/version.php
  - phpcs --report-full --standard=PSR2 install/*.php
  - phpcs --report-full --standard=PSR2 -n api/index.php
  - phpcs --report-full --standard=PSR2 -n include/colors.php
  - phpcs --report-full --standard=PSR2 -n include/db.php
  - phpcs --report-full --standard=PSR2 -n include/errorhandler.php
  - phpcs --report-full --standard=PSR2 -n include/functions.php
  - phpcs --report-full --standard=PSR2 -n include/rssfuncs.php
  - phpcs --report-full --standard=PSR2 -n include/sanity_check.php
  - phpcs --report-full --standard=PSR2 -n include/sessions.php
