language: php

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash

php:
  - 5.5
  - 5.6

script:
  - phpcs --report-full --standard=PSR2 include/ccache.php
  - phpcs --report-full --standard=PSR2 include/functions2.php
  - phpcs --report-full --standard=PSR2 -n include/colors.php
  - phpcs --report-full --standard=PSR2 -n include/functions.php
